name: publish

on:
  release:
    types: published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: buildx-

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      # login to docker hub
      - uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # login to github container registry
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - id: hub
        run: |
          echo "::set-output name=name::$(basename ${GITHUB_REPOSITORY/node-//})"
          echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      # publish
      - uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ${{ github.repository_owner }}/${{ steps.hub.outputs.name }}:latest
            ${{ github.repository_owner }}/${{ steps.hub.outputs.name }}:${{ steps.hub.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ steps.hub.outputs.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ steps.hub.outputs.name }}:${{ steps.hub.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ steps.hub.outputs.name }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.version=${{ steps.hub.outputs.version }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
